const words = [
    "2+ Meldungen",
    "Frank ist nicht in einem Büro",
    "Meeting startet 2+ Minuten zu früh oder zu spät",
    "Johannes/Oli schweifen ab",
    "Weniger als 14 Leute",
    "Oli hat nichts gemacht, außer Bord umzusortieren",
    "Eine Person verlässt den call",
    "Jemand hat vergessen sich zu entmuten",
    "Satz: Wer war noch nicht?",
    "Prod update rollback",
    "Holger yapping (2+ Minuten)",
    "Holger fake Backrgound",
    "Ich war dran",
    "Erinnert sich nicht an was gemacht",
    "Showstopper",
    "Oli schiebt verspätung auf Frank",
    "Unter 15 Minuten",
    "Jemand wird vergessen",
    "Devware rufen sich hintereinander auf",
    "2+ Webcams aus",
    "Doppelt aufgerufen",
    "Oli/Frank rufen Johannes direkt auf",
    "Hört man mich jetzt?",
    "Lucas/Stefan sind schatten",
    "Morris ist ein blob",
    "Flachwitz von Johannes",
    "Heute x Morgen x",
    "Oben Links ist... (von Oli)"
]

module.exports = words;
